Repository mj-will/nessai, pull requests merged in 2023-02, with the labels that each got.

#267 Remove nessai.gw.legacy
  CHANGELOG.md
  nessai/gw/legacy.py
  nessai/samplers/nestedsampler.py
  tests/test_gw/test_equivalent_proposal.py
  tests/test_gw/test_gw_legacy.py
  tests/test_samplers/test_nested_sampler/test_proposal_config.py
Labels: refactor, breaking changes

#268 Pin black to 2022 version
  .github/workflows/lint.yml
Labels: ci, style

#269 Change new shrinkage weights to be optional
  CHANGELOG.md
  nessai/evidence.py
  nessai/posterior.py
  nessai/samplers/nestedsampler.py
  tests/test_evidence.py
  tests/test_posterior.py
  tests/test_samplers/test_nested_sampler/test_general_config.py
Labels: enhancement

#270 Check extra flowproposal kwargs
  CHANGELOG.md
  examples/eggbox.py
  nessai/proposal/flowproposal.py
  nessai/proposal/utils.py
  nessai/samplers/nestedsampler.py
  tests/test_proposal/test_flowproposal/test_flowproposal_init_resume.py
  tests/test_proposal/test_utils.py
  tests/test_sampling.py
Labels: enhancement

#271 Refactor rescaling
  nessai/gw/proposal.py
  nessai/proposal/flowproposal.py
  nessai/reparameterisations/base.py
  nessai/reparameterisations/combined.py
  nessai/reparameterisations/rescale.py
  tests/test_gw/test_gw_proposal.py
  tests/test_proposal/test_flowproposal/test_flowproposal_add_reparam.py
  tests/test_proposal/test_flowproposal/test_flowproposal_configuration.py
  tests/test_proposal/test_flowproposal/test_flowproposal_init_resume.py
  tests/test_proposal/test_flowproposal/test_flowproposal_integration.py
  tests/test_proposal/test_flowproposal/test_flowproposal_rescaling.py
  tests/test_reparameterisations/test_base_reparameterisation.py
  tests/test_reparameterisations/test_combined.py
  tests/test_reparameterisations/test_rescale_to_bounds.py
  tests/test_sampling.py
Labels: refactor

#272 Rework nessai.config
  CHANGELOG.md
  nessai/config.py
  nessai/livepoint.py
  nessai/model.py
  nessai/plot.py
  nessai/proposal/augmented.py
  nessai/proposal/flowproposal.py
  nessai/samplers/nestedsampler.py
  tests/test_config.py
  tests/test_livepoint.py
  tests/test_plot.py
  tests/test_proposal/test_flowproposal/test_flowproposal_population.py
  tests/test_proposal/test_flowproposal/test_flowproposal_properties.py
  tests/test_utils/test_io_utils.py
Labels: bug, refactor, breaking changes

#273 Add ScaleAndShift reparameterisation
  CHANGELOG.md
  nessai/reparameterisations/__init__.py
  nessai/reparameterisations/rescale.py
  nessai/utils/testing.py
  tests/test_proposal/test_flowproposal/test_flowproposal_add_reparam.py
  tests/test_reparameterisations/conftest.py
  tests/test_reparameterisations/test_rescale.py
  tests/test_reparameterisations/test_scale_and_shift.py
  tests/test_utils/test_testing_utils.py
Labels: enhancement

#274 Update the result file format.
  CHANGELOG.md
  nessai/flowmodel/base.py
  nessai/flowsampler.py
  nessai/utils/__init__.py
  nessai/utils/io.py
  requirements.txt
  setup.cfg
  tests/test_flowsampler.py
  tests/test_sampling.py
  tests/test_utils/test_io_utils.py
Labels: enhancement, breaking changes

#276 Tweak logging statements
  nessai/samplers/nestedsampler.py
Labels: refactor

#275 Check invalid model config
  examples/gw/full_gw_example.py
  nessai/flowmodel/config.py
  nessai/flows/utils.py
  tests/test_flows/test_flow_utils.py
Labels: enhancement

#277 Optimise population function
  CHANGELOG.md
  nessai/model.py
  nessai/proposal/flowproposal.py
  nessai/utils/sampling.py
  tests/test_model.py
  tests/test_proposal/test_flowproposal/conftest.py
  tests/test_proposal/test_flowproposal/test_flowproposal_configuration.py
  tests/test_proposal/test_flowproposal/test_flowproposal_draw.py
  tests/test_proposal/test_flowproposal/test_flowproposal_flow.py
  tests/test_proposal/test_flowproposal/test_flowproposal_init_resume.py
  tests/test_proposal/test_flowproposal/test_flowproposal_population.py
  tests/test_utils/test_sampling_utils.py
Labels: refactor, optimisation

#278 Use default bilby logging level in examples
  examples/bilby_unbounded_priors.py
  examples/gw/basic_gw_example.py
  examples/gw/calibration_example.py
  examples/gw/full_gw_example.py
Labels: example

#279 Update GHA versions for pypi workflow
  .github/workflows/publish-to-pypi.yml
Labels: ci

#281 Ignore plotting errors for very large plots. Fixes #280
  nessai/plot.py
Labels: bug

#282 Add maximum figure size
  CHANGELOG.md
  nessai/config.py
  nessai/plot.py
  tests/test_plot.py
Labels: enhancement

#284 Fix in bounds bug
  nessai/model.py
  tests/test_model.py
Labels: bug
